artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/9afba9566233435ab575385b7a73b9e6/artifacts
end_time: 1720795289766
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9afba9566233435ab575385b7a73b9e6
run_name: big-shark-212
run_uuid: 9afba9566233435ab575385b7a73b9e6
source_name: ''
source_type: 4
source_version: ''
start_time: 1720795287735
status: 3
tags: []
user_id: menge
