artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/cdb4a87a271a4c23ba29352bf736d971/artifacts
end_time: 1720799614746
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: cdb4a87a271a4c23ba29352bf736d971
run_name: colorful-fox-727
run_uuid: cdb4a87a271a4c23ba29352bf736d971
source_name: ''
source_type: 4
source_version: ''
start_time: 1720799573501
status: 4
tags: []
user_id: menge
