artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/73267a3def3643bdb764f44b086fe0b1/artifacts
end_time: 1720796924331
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 73267a3def3643bdb764f44b086fe0b1
run_name: puzzled-pig-113
run_uuid: 73267a3def3643bdb764f44b086fe0b1
source_name: ''
source_type: 4
source_version: ''
start_time: 1720796922294
status: 3
tags: []
user_id: menge
