artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/5d075848427a4721a8d950dce668e091/artifacts
end_time: 1720795740930
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5d075848427a4721a8d950dce668e091
run_name: intelligent-crow-326
run_uuid: 5d075848427a4721a8d950dce668e091
source_name: ''
source_type: 4
source_version: ''
start_time: 1720795738894
status: 3
tags: []
user_id: menge
