artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/9da897b60dd147779738147e3cafb4c3/artifacts
end_time: 1720790599188
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9da897b60dd147779738147e3cafb4c3
run_name: bustling-cod-463
run_uuid: 9da897b60dd147779738147e3cafb4c3
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790597276
status: 4
tags: []
user_id: menge
