artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/ad00e3fb6006489b81f631f368f6c487/artifacts
end_time: 1720794738675
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ad00e3fb6006489b81f631f368f6c487
run_name: melodic-grub-888
run_uuid: ad00e3fb6006489b81f631f368f6c487
source_name: ''
source_type: 4
source_version: ''
start_time: 1720794736632
status: 3
tags: []
user_id: menge
