artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/a9f8a01e97624752a9d293af0178d0a1/artifacts
end_time: 1720790355196
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a9f8a01e97624752a9d293af0178d0a1
run_name: monumental-zebra-536
run_uuid: a9f8a01e97624752a9d293af0178d0a1
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790353283
status: 4
tags: []
user_id: menge
