artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/6aaa32a4a3ae49039f58fbd4b58d0dca/artifacts
end_time: 1720796520330
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6aaa32a4a3ae49039f58fbd4b58d0dca
run_name: amusing-stork-771
run_uuid: 6aaa32a4a3ae49039f58fbd4b58d0dca
source_name: ''
source_type: 4
source_version: ''
start_time: 1720796518340
status: 3
tags: []
user_id: menge
