artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/a9692641bb7a429b873a1a58fdd14592/artifacts
end_time: 1720797602119
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a9692641bb7a429b873a1a58fdd14592
run_name: skillful-stag-962
run_uuid: a9692641bb7a429b873a1a58fdd14592
source_name: ''
source_type: 4
source_version: ''
start_time: 1720797601978
status: 3
tags: []
user_id: menge
