artifact_location: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0
creation_time: 1720785396132
experiment_id: '0'
last_update_time: 1720785396132
lifecycle_stage: active
name: Default
