artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/fa270033b22848729de01682b7e42829/artifacts
end_time: 1720790635675
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: fa270033b22848729de01682b7e42829
run_name: thoughtful-yak-797
run_uuid: fa270033b22848729de01682b7e42829
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790633788
status: 4
tags: []
user_id: menge
