artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/f3b4871cf4ca429babc4c4e75a3ab6d4/artifacts
end_time: 1720796609173
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f3b4871cf4ca429babc4c4e75a3ab6d4
run_name: auspicious-sow-47
run_uuid: f3b4871cf4ca429babc4c4e75a3ab6d4
source_name: ''
source_type: 4
source_version: ''
start_time: 1720796607188
status: 3
tags: []
user_id: menge
