artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/fabfafd902d74d7e8158290ca047ca40/artifacts
end_time: 1720800012338
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: fabfafd902d74d7e8158290ca047ca40
run_name: flawless-donkey-395
run_uuid: fabfafd902d74d7e8158290ca047ca40
source_name: ''
source_type: 4
source_version: ''
start_time: 1720800010107
status: 3
tags: []
user_id: menge
