artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/af4dc5760e64444d99859039d74f052b/artifacts
end_time: 1720800014902
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: af4dc5760e64444d99859039d74f052b
run_name: angry-owl-360
run_uuid: af4dc5760e64444d99859039d74f052b
source_name: ''
source_type: 4
source_version: ''
start_time: 1720800012345
status: 3
tags: []
user_id: menge
