artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/907b5247f5a5431aa2b6fa5a68451162/artifacts
end_time: 1720790495128
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 907b5247f5a5431aa2b6fa5a68451162
run_name: valuable-perch-59
run_uuid: 907b5247f5a5431aa2b6fa5a68451162
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790493271
status: 3
tags: []
user_id: menge
