artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/b444ccb7469a4b37a7c77348aed15193/artifacts
end_time: 1720791280762
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b444ccb7469a4b37a7c77348aed15193
run_name: welcoming-whale-70
run_uuid: b444ccb7469a4b37a7c77348aed15193
source_name: ''
source_type: 4
source_version: ''
start_time: 1720791278901
status: 3
tags: []
user_id: menge
