artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/7341acf837474e0b89735949e20e51a1/artifacts
end_time: 1720794573594
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7341acf837474e0b89735949e20e51a1
run_name: luminous-trout-339
run_uuid: 7341acf837474e0b89735949e20e51a1
source_name: ''
source_type: 4
source_version: ''
start_time: 1720794571664
status: 3
tags: []
user_id: menge
