artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/0fc68db306b2423388eeac367df41e13/artifacts
end_time: 1720791884019
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0fc68db306b2423388eeac367df41e13
run_name: glamorous-gull-362
run_uuid: 0fc68db306b2423388eeac367df41e13
source_name: ''
source_type: 4
source_version: ''
start_time: 1720791882031
status: 3
tags: []
user_id: menge
