artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/dc0fdce935554c24bc41b8a84b5febc6/artifacts
end_time: 1720799991344
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: dc0fdce935554c24bc41b8a84b5febc6
run_name: rare-mink-284
run_uuid: dc0fdce935554c24bc41b8a84b5febc6
source_name: ''
source_type: 4
source_version: ''
start_time: 1720799954384
status: 3
tags: []
user_id: menge
