artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/0e56fefd79ba4aaaa83003a0c6088722/artifacts
end_time: 1720790296890
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0e56fefd79ba4aaaa83003a0c6088722
run_name: bustling-vole-798
run_uuid: 0e56fefd79ba4aaaa83003a0c6088722
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790293453
status: 4
tags: []
user_id: menge
