artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/0ff69146f39a4cef9adf385e23d12900/artifacts
end_time: 1720797040538
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0ff69146f39a4cef9adf385e23d12900
run_name: caring-steed-833
run_uuid: 0ff69146f39a4cef9adf385e23d12900
source_name: ''
source_type: 4
source_version: ''
start_time: 1720797038581
status: 3
tags: []
user_id: menge
