artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/8b07e6364d5c4fca885eba578fb81822/artifacts
end_time: 1720790254353
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8b07e6364d5c4fca885eba578fb81822
run_name: painted-panda-602
run_uuid: 8b07e6364d5c4fca885eba578fb81822
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790254331
status: 4
tags: []
user_id: menge
