artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/2d52bf6b11a549c7b7e682bd6c1f2446/artifacts
end_time: 1720790197071
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2d52bf6b11a549c7b7e682bd6c1f2446
run_name: luminous-deer-172
run_uuid: 2d52bf6b11a549c7b7e682bd6c1f2446
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790196873
status: 4
tags: []
user_id: menge
