artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/a760277dd7244d26813a8a0798cb83ee/artifacts
end_time: 1720790672539
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a760277dd7244d26813a8a0798cb83ee
run_name: resilient-gull-960
run_uuid: a760277dd7244d26813a8a0798cb83ee
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790670672
status: 3
tags: []
user_id: menge
