artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/341b789b48d94125957bbff66620c0c5/artifacts
end_time: 1720799951710
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 341b789b48d94125957bbff66620c0c5
run_name: enchanting-fowl-327
run_uuid: 341b789b48d94125957bbff66620c0c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1720799949509
status: 3
tags: []
user_id: menge
