artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/e81fc0bd5c4a46e2afebae264de0e36d/artifacts
end_time: 1720795270708
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e81fc0bd5c4a46e2afebae264de0e36d
run_name: efficient-snake-296
run_uuid: e81fc0bd5c4a46e2afebae264de0e36d
source_name: ''
source_type: 4
source_version: ''
start_time: 1720795268550
status: 3
tags: []
user_id: menge
