artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/6613b49b745c4df6a75c2b78d1a6fc7b/artifacts
end_time: 1720799994024
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6613b49b745c4df6a75c2b78d1a6fc7b
run_name: beautiful-shark-270
run_uuid: 6613b49b745c4df6a75c2b78d1a6fc7b
source_name: ''
source_type: 4
source_version: ''
start_time: 1720799991350
status: 3
tags: []
user_id: menge
