artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/0d9222268e7641fe8a79e51b08355020/artifacts
end_time: 1720792047584
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0d9222268e7641fe8a79e51b08355020
run_name: awesome-smelt-787
run_uuid: 0d9222268e7641fe8a79e51b08355020
source_name: ''
source_type: 4
source_version: ''
start_time: 1720792045593
status: 3
tags: []
user_id: menge
