artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/62999e3fa5c84381bb71856109c1de13/artifacts
end_time: 1720796132713
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 62999e3fa5c84381bb71856109c1de13
run_name: industrious-owl-923
run_uuid: 62999e3fa5c84381bb71856109c1de13
source_name: ''
source_type: 4
source_version: ''
start_time: 1720796130704
status: 3
tags: []
user_id: menge
