artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/12c69c0c01434998bed2c94da8126753/artifacts
end_time: 1720800051712
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 12c69c0c01434998bed2c94da8126753
run_name: caring-conch-646
run_uuid: 12c69c0c01434998bed2c94da8126753
source_name: ''
source_type: 4
source_version: ''
start_time: 1720800014913
status: 3
tags: []
user_id: menge
