artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/ca550cfd96e641f19247c997d9edc7dc/artifacts
end_time: 1720790359047
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ca550cfd96e641f19247c997d9edc7dc
run_name: placid-shrike-775
run_uuid: ca550cfd96e641f19247c997d9edc7dc
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790357161
status: 4
tags: []
user_id: menge
