artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/2080603658bf4e75832df06dfc11197c/artifacts
end_time: 1720798308639
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2080603658bf4e75832df06dfc11197c
run_name: dazzling-lamb-279
run_uuid: 2080603658bf4e75832df06dfc11197c
source_name: ''
source_type: 4
source_version: ''
start_time: 1720798267911
status: 4
tags: []
user_id: menge
