artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/3e5e80e50e0845308099114e6deb7c4b/artifacts
end_time: 1720799811048
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3e5e80e50e0845308099114e6deb7c4b
run_name: crawling-bee-367
run_uuid: 3e5e80e50e0845308099114e6deb7c4b
source_name: ''
source_type: 4
source_version: ''
start_time: 1720799811003
status: 4
tags: []
user_id: menge
