artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/4660588e396a4ed59c3ec147bce1988c/artifacts
end_time: 1720790454217
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4660588e396a4ed59c3ec147bce1988c
run_name: aged-conch-188
run_uuid: 4660588e396a4ed59c3ec147bce1988c
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790451599
status: 4
tags: []
user_id: menge
