artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/cdc307133ee644ccb90399cfb385e6aa/artifacts
end_time: 1720790220156
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: cdc307133ee644ccb90399cfb385e6aa
run_name: tasteful-gnu-129
run_uuid: cdc307133ee644ccb90399cfb385e6aa
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790220101
status: 4
tags: []
user_id: menge
