artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/e7bfda7d717342b58f9569513180dfb1/artifacts
end_time: 1720798160844
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e7bfda7d717342b58f9569513180dfb1
run_name: bald-newt-218
run_uuid: e7bfda7d717342b58f9569513180dfb1
source_name: ''
source_type: 4
source_version: ''
start_time: 1720798120075
status: 4
tags: []
user_id: menge
