artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/f7e0945e64bc4a92aad5360ec58d7737/artifacts
end_time: 1720796220969
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f7e0945e64bc4a92aad5360ec58d7737
run_name: vaunted-mink-0
run_uuid: f7e0945e64bc4a92aad5360ec58d7737
source_name: ''
source_type: 4
source_version: ''
start_time: 1720796218902
status: 3
tags: []
user_id: menge
