artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/a1148a4606be4cfcafcf9b479f81c90e/artifacts
end_time: 1720799854221
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a1148a4606be4cfcafcf9b479f81c90e
run_name: languid-wren-104
run_uuid: a1148a4606be4cfcafcf9b479f81c90e
source_name: ''
source_type: 4
source_version: ''
start_time: 1720799854058
status: 4
tags: []
user_id: menge
