artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/acf7e3dea52349fda7cf44fb4246ae1f/artifacts
end_time: 1720793779093
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: acf7e3dea52349fda7cf44fb4246ae1f
run_name: resilient-squid-231
run_uuid: acf7e3dea52349fda7cf44fb4246ae1f
source_name: ''
source_type: 4
source_version: ''
start_time: 1720793777044
status: 3
tags: []
user_id: menge
