artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/e960d40cec934ef3bc0447a7972effe2/artifacts
end_time: 1720795609316
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e960d40cec934ef3bc0447a7972effe2
run_name: honorable-snake-866
run_uuid: e960d40cec934ef3bc0447a7972effe2
source_name: ''
source_type: 4
source_version: ''
start_time: 1720795607242
status: 3
tags: []
user_id: menge
