artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/2bbd3c49b1174b4db4c6d74f0fa33ef4/artifacts
end_time: 1720796729780
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2bbd3c49b1174b4db4c6d74f0fa33ef4
run_name: bemused-wasp-295
run_uuid: 2bbd3c49b1174b4db4c6d74f0fa33ef4
source_name: ''
source_type: 4
source_version: ''
start_time: 1720796727720
status: 3
tags: []
user_id: menge
