artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/968e3a2dc9a34f7da95adffdb64a8fce/artifacts
end_time: 1720785400546
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 968e3a2dc9a34f7da95adffdb64a8fce
run_name: big-frog-79
run_uuid: 968e3a2dc9a34f7da95adffdb64a8fce
source_name: ''
source_type: 4
source_version: ''
start_time: 1720785396200
status: 4
tags: []
user_id: philippemenge
