artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/84bd66a70b224bcda6182af0139218f5/artifacts
end_time: 1720799954375
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 84bd66a70b224bcda6182af0139218f5
run_name: whimsical-sloth-185
run_uuid: 84bd66a70b224bcda6182af0139218f5
source_name: ''
source_type: 4
source_version: ''
start_time: 1720799951716
status: 3
tags: []
user_id: menge
