artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/dc82502645c74e73abb80113988b7440/artifacts
end_time: 1720790325952
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: dc82502645c74e73abb80113988b7440
run_name: spiffy-crow-396
run_uuid: dc82502645c74e73abb80113988b7440
source_name: ''
source_type: 4
source_version: ''
start_time: 1720790324002
status: 4
tags: []
user_id: menge
