artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/57c17799866849f5baaad297ac137ec6/artifacts
end_time: 1720795300443
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 57c17799866849f5baaad297ac137ec6
run_name: traveling-midge-722
run_uuid: 57c17799866849f5baaad297ac137ec6
source_name: ''
source_type: 4
source_version: ''
start_time: 1720795298510
status: 3
tags: []
user_id: menge
