artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/c577b079ec7e4e1e9b6ee4408764618d/artifacts
end_time: 1720795199898
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c577b079ec7e4e1e9b6ee4408764618d
run_name: exultant-crow-964
run_uuid: c577b079ec7e4e1e9b6ee4408764618d
source_name: ''
source_type: 4
source_version: ''
start_time: 1720795197920
status: 3
tags: []
user_id: menge
