artifact_uri: /Users/philippemenge/Dev/P6/GDI2/Projeto-Data-Science/your_tracking_uri/0/f357221ec6f94ee1b11ecb3687f218ca/artifacts
end_time: 1720798005799
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f357221ec6f94ee1b11ecb3687f218ca
run_name: skillful-lamb-158
run_uuid: f357221ec6f94ee1b11ecb3687f218ca
source_name: ''
source_type: 4
source_version: ''
start_time: 1720798005638
status: 4
tags: []
user_id: menge
